'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Interactive Spectral Exploration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _MetaFilter = require('./MetaFilter');

var _MetaFilter2 = _interopRequireDefault(_MetaFilter);

var _Stat = require('./Stat');

var _Stat2 = _interopRequireDefault(_Stat);

var _StatFilter = require('./StatFilter');

var _StatFilter2 = _interopRequireDefault(_StatFilter);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The AnalysisQuery model module.
* @module model/AnalysisQuery
* @version 1.0.0
*/
var AnalysisQuery = function () {
    /**
    * Constructs a new <code>AnalysisQuery</code>.
    * @alias module:model/AnalysisQuery
    * @class
    */

    function AnalysisQuery() {
        _classCallCheck(this, AnalysisQuery);

        this['stats'] = undefined;
        this['meta'] = undefined;
        this['x'] = undefined;
        this['y'] = undefined;
        this['z'] = undefined;
        this['includeMeta'] = undefined;
        this['limit'] = 100;
    }

    /**
    * Constructs a <code>AnalysisQuery</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AnalysisQuery} obj Optional instance to populate.
    * @return {module:model/AnalysisQuery} The populated <code>AnalysisQuery</code> instance.
    */


    _createClass(AnalysisQuery, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new AnalysisQuery();

                if (data.hasOwnProperty('stats')) {
                    obj['stats'] = _ApiClient2.default.convertToType(data['stats'], [_StatFilter2.default]);
                }
                if (data.hasOwnProperty('meta')) {
                    obj['meta'] = _ApiClient2.default.convertToType(data['meta'], [_MetaFilter2.default]);
                }
                if (data.hasOwnProperty('x')) {
                    obj['x'] = _Stat2.default.constructFromObject(data['x']);
                }
                if (data.hasOwnProperty('y')) {
                    obj['y'] = _Stat2.default.constructFromObject(data['y']);
                }
                if (data.hasOwnProperty('z')) {
                    obj['z'] = _Stat2.default.constructFromObject(data['z']);
                }
                if (data.hasOwnProperty('includeMeta')) {
                    obj['includeMeta'] = _ApiClient2.default.convertToType(data['includeMeta'], ['String']);
                }
                if (data.hasOwnProperty('limit')) {
                    obj['limit'] = _ApiClient2.default.convertToType(data['limit'], 'Number');
                }
            }
            return obj;
        }

        /**
        * @member {Array.<module:model/StatFilter>} stats
        */

        /**
        * @member {Array.<module:model/MetaFilter>} meta
        */

        /**
        * @member {module:model/Stat} x
        */

        /**
        * @member {module:model/Stat} y
        */

        /**
        * @member {module:model/Stat} z
        */

        /**
        * @member {Array.<String>} includeMeta
        */

        /**
        * @member {Number} limit
        * @default 100
        */

    }]);

    return AnalysisQuery;
}();

exports.default = AnalysisQuery;