'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Interactive Spectral Exploration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The AnalysedSlice model module.
* @module model/AnalysedSlice
* @version 1.0.0
*/
var AnalysedSlice = function () {
    /**
    * Constructs a new <code>AnalysedSlice</code>.
    * @alias module:model/AnalysedSlice
    * @class
    */

    function AnalysedSlice() {
        _classCallCheck(this, AnalysedSlice);

        this['id'] = undefined;
        this['name'] = undefined;
        this['file'] = undefined;
        this['start'] = undefined;
        this['end'] = undefined;
        this['duration'] = undefined;
        this['meta'] = undefined;
        this['x'] = undefined;
        this['y'] = undefined;
        this['z'] = undefined;
    }

    /**
    * Constructs a <code>AnalysedSlice</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AnalysedSlice} obj Optional instance to populate.
    * @return {module:model/AnalysedSlice} The populated <code>AnalysedSlice</code> instance.
    */


    _createClass(AnalysedSlice, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new AnalysedSlice();

                if (data.hasOwnProperty('id')) {
                    obj['id'] = _ApiClient2.default.convertToType(data['id'], 'Number');
                }
                if (data.hasOwnProperty('name')) {
                    obj['name'] = _ApiClient2.default.convertToType(data['name'], 'String');
                }
                if (data.hasOwnProperty('file')) {
                    obj['file'] = _ApiClient2.default.convertToType(data['file'], 'String');
                }
                if (data.hasOwnProperty('start')) {
                    obj['start'] = _ApiClient2.default.convertToType(data['start'], 'Number');
                }
                if (data.hasOwnProperty('end')) {
                    obj['end'] = _ApiClient2.default.convertToType(data['end'], 'Number');
                }
                if (data.hasOwnProperty('duration')) {
                    obj['duration'] = _ApiClient2.default.convertToType(data['duration'], 'Number');
                }
                if (data.hasOwnProperty('meta')) {
                    obj['meta'] = _ApiClient2.default.convertToType(data['meta'], { 'String': 'String' });
                }
                if (data.hasOwnProperty('x')) {
                    obj['x'] = _ApiClient2.default.convertToType(data['x'], 'Number');
                }
                if (data.hasOwnProperty('y')) {
                    obj['y'] = _ApiClient2.default.convertToType(data['y'], 'Number');
                }
                if (data.hasOwnProperty('z')) {
                    obj['z'] = _ApiClient2.default.convertToType(data['z'], 'Number');
                }
            }
            return obj;
        }

        /**
        * @member {Number} id
        */

        /**
        * @member {String} name
        */

        /**
        * @member {String} file
        */

        /**
        * @member {Number} start
        */

        /**
        * @member {Number} end
        */

        /**
        * @member {Number} duration
        */

        /**
        * @member {Object.<String, String>} meta
        */

        /**
        * @member {Number} x
        */

        /**
        * @member {Number} y
        */

        /**
        * @member {Number} z
        */

    }]);

    return AnalysedSlice;
}();

exports.default = AnalysedSlice;