'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Swagger Petstore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _NumericRangeFilter = require('./NumericRangeFilter');

var _NumericRangeFilter2 = _interopRequireDefault(_NumericRangeFilter);

var _PropertyFilter = require('./PropertyFilter');

var _PropertyFilter2 = _interopRequireDefault(_PropertyFilter);

var _Stat = require('./Stat');

var _Stat2 = _interopRequireDefault(_Stat);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The Query model module.
* @module model/Query
* @version 1.0.0
*/
var Query = function () {
    /**
    * Constructs a new <code>Query</code>.
    * @alias module:model/Query
    * @class
    */

    function Query() {
        _classCallCheck(this, Query);

        this['ranges'] = undefined;
        this['properties'] = undefined;
        this['x'] = undefined;
        this['y'] = undefined;
        this['z'] = undefined;
        this['limit'] = 100;
    }

    /**
    * Constructs a <code>Query</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Query} obj Optional instance to populate.
    * @return {module:model/Query} The populated <code>Query</code> instance.
    */


    _createClass(Query, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new Query();

                if (data.hasOwnProperty('ranges')) {
                    obj['ranges'] = _ApiClient2.default.convertToType(data['ranges'], [_NumericRangeFilter2.default]);
                }
                if (data.hasOwnProperty('properties')) {
                    obj['properties'] = _ApiClient2.default.convertToType(data['properties'], [_PropertyFilter2.default]);
                }
                if (data.hasOwnProperty('x')) {
                    obj['x'] = _Stat2.default.constructFromObject(data['x']);
                }
                if (data.hasOwnProperty('y')) {
                    obj['y'] = _Stat2.default.constructFromObject(data['y']);
                }
                if (data.hasOwnProperty('z')) {
                    obj['z'] = _Stat2.default.constructFromObject(data['z']);
                }
                if (data.hasOwnProperty('limit')) {
                    obj['limit'] = _ApiClient2.default.convertToType(data['limit'], 'Number');
                }
            }
            return obj;
        }

        /**
        * @member {Array.<module:model/NumericRangeFilter>} ranges
        */

        /**
        * @member {Array.<module:model/PropertyFilter>} properties
        */

        /**
        * @member {module:model/Stat} x
        */

        /**
        * @member {module:model/Stat} y
        */

        /**
        * @member {module:model/Stat} z
        */

        /**
        * @member {Number} limit
        * @default 100
        */

    }]);

    return Query;
}();

exports.default = Query;