'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Interactive Spectral Exploration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _Stat = require('./Stat');

var _Stat2 = _interopRequireDefault(_Stat);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* The StatFilter model module.
* @module model/StatFilter
* @version 1.0.0
*/
var StatFilter = function () {
    /**
    * Constructs a new <code>StatFilter</code>.
    * @alias module:model/StatFilter
    * @class
    */

    function StatFilter() {
        _classCallCheck(this, StatFilter);

        this['stat'] = undefined;
        this['start'] = undefined;
        this['end'] = undefined;
    }

    /**
    * Constructs a <code>StatFilter</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StatFilter} obj Optional instance to populate.
    * @return {module:model/StatFilter} The populated <code>StatFilter</code> instance.
    */


    _createClass(StatFilter, null, [{
        key: 'constructFromObject',
        value: function constructFromObject(data, obj) {
            if (data) {
                obj = obj || new StatFilter();

                if (data.hasOwnProperty('stat')) {
                    obj['stat'] = _Stat2.default.constructFromObject(data['stat']);
                }
                if (data.hasOwnProperty('start')) {
                    obj['start'] = _ApiClient2.default.convertToType(data['start'], 'Number');
                }
                if (data.hasOwnProperty('end')) {
                    obj['end'] = _ApiClient2.default.convertToType(data['end'], 'Number');
                }
            }
            return obj;
        }

        /**
        * @member {module:model/Stat} stat
        */

        /**
        * @member {Number} start
        */

        /**
        * @member {Number} end
        */

    }]);

    return StatFilter;
}();

exports.default = StatFilter;