'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Swagger Petstore
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * OpenAPI spec version: 1.0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * NOTE: This class is auto generated by the swagger code generator program.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * https://github.com/swagger-api/swagger-codegen.git
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Do not edit the class manually.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */

var _ApiClient = require('../ApiClient');

var _ApiClient2 = _interopRequireDefault(_ApiClient);

var _Query = require('../model/Query');

var _Query2 = _interopRequireDefault(_Query);

var _Slice = require('../model/Slice');

var _Slice2 = _interopRequireDefault(_Slice);

var _SupportedFilters = require('../model/SupportedFilters');

var _SupportedFilters2 = _interopRequireDefault(_SupportedFilters);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

/**
* InCorpEx service.
* @module api/InCorpExApi
* @version 1.0.0
*/
var InCorpExApi = function () {

  /**
  * Constructs a new InCorpExApi. 
  * @alias module:api/InCorpExApi
  * @class
  * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
  * default to {@link module:ApiClient#instance} if unspecified.
  */
  function InCorpExApi(apiClient) {
    _classCallCheck(this, InCorpExApi);

    this.apiClient = apiClient || _ApiClient2.default.instance;
  }

  /**
   * Callback function to receive the result of the getFilters operation.
   * @callback module:api/InCorpExApi~getFiltersCallback
   * @param {String} error Error message, if any.
   * @param {module:model/SupportedFilters} data The data returned by the service call.
   * @param {String} response The complete HTTP response.
   */

  /**
   * Get supporter filters
   * @param {module:api/InCorpExApi~getFiltersCallback} callback The callback function, accepting three arguments: error, data, response
   * data is of type: {@link module:model/SupportedFilters}
   */


  _createClass(InCorpExApi, [{
    key: 'getFilters',
    value: function getFilters(callback) {
      var postBody = null;

      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = _SupportedFilters2.default;

      return this.apiClient.callApi('/filters', 'GET', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType, callback);
    }
    /**
     * Callback function to receive the result of the runAnalysis operation.
     * @callback module:api/InCorpExApi~runAnalysisCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Slice>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Run an analysis
     * @param {Object} opts Optional parameters
     * @param {module:api/InCorpExApi~runAnalysisCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Slice>}
     */

  }, {
    key: 'runAnalysis',
    value: function runAnalysis(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      var pathParams = {};
      var queryParams = {};
      var headerParams = {};
      var formParams = {};

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [_Slice2.default];

      return this.apiClient.callApi('/analysis', 'POST', pathParams, queryParams, headerParams, formParams, postBody, authNames, contentTypes, accepts, returnType, callback);
    }
  }]);

  return InCorpExApi;
}();

exports.default = InCorpExApi;