/**
 * Interactive Spectral Exploration
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AnalysedSlice from './model/AnalysedSlice';
import AnalysisQuery from './model/AnalysisQuery';
import MetaFilter from './model/MetaFilter';
import Slice from './model/Slice';
import Stat from './model/Stat';
import StatFilter from './model/StatFilter';
import SupportedFilters from './model/SupportedFilters';
import InSpExApi from './api/InSpExApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var InteractiveSpectralExploration = require('index'); // See note below*.
* var xxxSvc = new InteractiveSpectralExploration.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new InteractiveSpectralExploration.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new InteractiveSpectralExploration.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new InteractiveSpectralExploration.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnalysedSlice model constructor.
     * @property {module:model/AnalysedSlice}
     */
    AnalysedSlice,

    /**
     * The AnalysisQuery model constructor.
     * @property {module:model/AnalysisQuery}
     */
    AnalysisQuery,

    /**
     * The MetaFilter model constructor.
     * @property {module:model/MetaFilter}
     */
    MetaFilter,

    /**
     * The Slice model constructor.
     * @property {module:model/Slice}
     */
    Slice,

    /**
     * The Stat model constructor.
     * @property {module:model/Stat}
     */
    Stat,

    /**
     * The StatFilter model constructor.
     * @property {module:model/StatFilter}
     */
    StatFilter,

    /**
     * The SupportedFilters model constructor.
     * @property {module:model/SupportedFilters}
     */
    SupportedFilters,

    /**
    * The InSpExApi service constructor.
    * @property {module:api/InSpExApi}
    */
    InSpExApi
};
